project_id: arun-genai-bb
credentials_json: ./credentials/key.json
datastore_id: moodys-demo-doc-search_1703646486907
user_pseudo_id: 12345
text_embed_model_name: text-gecko@latest
text_gen_model_name: gemini-pro@latest